#!/bin/bash

set -e
. /usr/share/debconf/confmodule

case "$1" in
  remove|deconfigure|abort-install)
    rm -f /var/tmp/bitcoin-install.flag
    systemctl is-enabled bitcoind >/dev/null && systemctl disable bitcoind >/dev/null || true
    systemctl status bitcoind >/dev/null && systemctl stop bitcoind >/dev/null || true
    pkill -9 -u bitcoin > /dev/null 2>&1 || true
    getent passwd bitcoin >/dev/null && userdel bitcoin >/dev/null 2>&1 || true
  ;;
esac

exit 0
